apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  # 指定   storageClass
  storageClassName: redis-nfs-storage-class
  nfs:
    path: /nfs-data/redis-data
    server: 192.168.0.58
