apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
spec:
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis-stack
          image: redis/redis-stack:7.0.2-RC2
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 6379
            - containerPort: 8001