apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  selector:
    app: redis-stack
  ports:
  - name: redis-stack-port
    port: 6380
    targetPort: 6379
    protocol: TCP 
    nodePort: 30380
  - name: redis-stack-web-port
    port: 8001
    targetPort: 8001
    protocol: TCP
    nodePort: 30381
  type: NodePort