apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoppscotch
  template:
    metadata:
      labels:
        app: hoppscotch
    spec:
      containers:
        - name: hoppscotch
          image: hoppscotch/hoppscotch:v2.2.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hoppscotch-service
spec:
  selector:
    app: hoppscotch
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch-ingress
spec:
  ingressClassName: ingress-cls
  rules:
    - host: api.muan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-service
                port:
                  number: 80
